src/Entity/News.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NewsRepository")
 * @Vich\Uploadable()
 */
class News
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $category_id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $description_short;

    /**
     * @ORM\Column(type="string", length=1000)
     */
    private $description_long;

    /**
     * @ORM\Column(type="datetime")
     */
    private $datetime;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="news_image", fileNameProperty="image")
     */
    private $imageFile;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="CategoryId")
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comments", mappedBy="news")
     */
    private $comments;


    /**
     * @return mixed
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param mixed $imageFile
     * @throws \Exception
     */
    public function setImageFile($imageFile): void
    {
        $this->imageFile = $imageFile;
    }


    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategoryId(): ?int
    {
        return $this->category_id;
    }

    public function setCategoryId (int $category_id): self
    {
        $this->category_id = $category_id;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescriptionShort(): ?string
    {
        return $this->description_short;
    }

    public function setDescriptionShort(string $description_short): self
    {
        $this->description_short = $description_short;

        return $this;
    }

    public function getDescriptionLong(): ?string
    {
        return $this->description_long;
    }

    public function setDescriptionLong(string $description_long): self
    {
        $this->description_long = $description_long;

        return $this;
    }

    public function getDatetime(): ?\DateTimeInterface
    {
        return $this->datetime;
    }

    public function setDatetime(\DateTimeInterface $datetime): self
    {
        $this->datetime = $datetime;

        return $this;
    }


    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }


    public function __toString()
    {
        return $this->title;
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComments(Comments $comments): self
    {
        if (!$this->comments->contains($comments)) {
            $this->comments[] = $comments;
            $comments->setNews($this);
        }

        return $this;
    }

    public function removeComments(Comments $comments): self
    {
        if ($this->comments->contains($comments)) {
            $this->comments->removeElement($comments);
            // set the owning side to null (unless already changed)
            if ($comments->getNews() === $this) {
                $comments->setNews(null);
            }
        }

        return $this;
    }

}

src/Form/NewsType.php
<?php

namespace App\Form;

use App\Entity\News;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class NewsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('category_id', EntityType::class,[
                'class' => 'App:Category',
                'choice_label' => 'title',
            ])
            ->add('title')
            ->add('description_short')
            ->add('description_long', TextareaType::class, ['attr'=> array('rows' => 5 , 'cols' => 70)])
            ->add('datetime')
            /*
            ->add('imageFile', FileType::class, [
                'mapped' => false,
                //'required' => false,
            ])*/;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => News::class,
        ]);
    }
}

src/Controller/NewsController.php
<?php

namespace App\Controller;

use App\Entity\Comments;
use App\Entity\News;
use App\Form\NewsType;
use App\Repository\CommentsRepository;
use App\Repository\NewsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Gedmo\Sluggable\Util\Urlizer;

/**
 * @Route("/news")
 */
class NewsController extends AbstractController
{
    /**
     * @Route("/{page<\d+>?1}", name="news_index", methods={"GET"})
     */
    public function index($page = 1, NewsRepository $newsRepository): Response
    {

        if (empty($page)) $page = 1;

        // ... get posts from DB...
        // Controller Action
        $newsAll = $newsRepository->getAllNews($page); // Returns 5 posts out of 20

        // You can also call the count methods (check PHPDoc for `paginate()`)
        # Total fetched (ie: `5` posts)
        $totalPostsReturned = $newsAll->getIterator()->count();

        # Count of ALL posts (ie: `20` posts)
        $totalPosts = $newsAll->count();

        # ArrayIterator
        $iterator = $newsAll->getIterator();

        $limit = 5;
        $maxPages = ceil($totalPosts / $limit);


        return $this->render('news/index.html.twig', [
            'news' => $newsAll, //$newsRepository->findAll(),
            'categories',
            'maxPages' => $maxPages,
            'thisPage'=> $page
        ]);
    }

    /**
     * @Route("/new", name="news_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $news = new News();
        $form = $this->createForm(NewsType::class, $news);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($news);
            $entityManager->flush();

            return $this->redirectToRoute('news_index');
        }

        return $this->render('news/new.html.twig', [
            'news' => $news,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/show/{id}", name="news_show", methods={"GET","POST"})
     */
    public function show(News $news, Request $request): Response
    {
        //$comments = $commentRepository->findBy(['news' => $news]);
        $comments = $news->getComments();

        $comment = new Comments();
        $form = $this->createFormBuilder($comment)
            ->add('comment',     TextareaType::class, [
                //'data' => 'hello',
                'attr' => ['rows' => 3, 'cols' => 35],
            ])
            ->getForm();


        //$request = $this->get('request');

        if ($request->getMethod() == 'POST')
        {
            $form->handleRequest($request);
            if ($form->isValid()) {
                $news->addComments($comment);
                $em = $this->getDoctrine()->getManager();
                $em->persist($news);
                $em->persist($comment);
                $em->flush();
            }
        }



        return $this->render('news/show.html.twig', [
            'news' => $news,
            'comments' => $comments,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/{id}/edit", name="news_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, News $news): Response
    {
        $form = $this->createForm(NewsType::class, $news);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('news_index');
        }

        return $this->render('news/edit.html.twig', [
            'news' => $news,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="news_delete", methods={"DELETE"})
     */
    public function delete(Request $request, News $news): Response
    {
        if ($this->isCsrfTokenValid('delete'.$news->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($news);
            $entityManager->flush();
        }

        return $this->redirectToRoute('news_index');
    }

    /**
     * @Route("/newsByCategory/{categoryId<\d+>}/{page<\d+>?1}", name="news_by_category")
     */
    public function newsByCategory($categoryId, $page = 1, NewsRepository $newsRepository) : Response
    {
        if (empty($page)) $page = 1;
        if (empty($categoryId)) $categoryId  = 1;

        // ... get posts from DB...
        // Controller Action
        $newsAll = $newsRepository->getAllNews($page, $categoryId); // Returns 5 posts out of 20

        // You can also call the count methods (check PHPDoc for `paginate()`)
        # Total fetched (ie: `5` posts)
        $totalPostsReturned = $newsAll->getIterator()->count();

        # Count of ALL posts
        $totalPosts = $newsAll->count();

        # ArrayIterator
        $iterator = $newsAll->getIterator();

        $limit = 5;
        $maxPages = ceil($totalPosts / $limit);


        return $this->render('news/index.html.twig', [
            'news' => $newsAll,
            'categories',
            'maxPages' => $maxPages,
            'thisPage'=> $page
        ]);

    }
}

templates/news/_delete_form.html.twig
<form method="post" action="{{ path('news_delete', {'id': news.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ news.id) }}">
    <button class="btn">Delete</button>
</form>

templates/news/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/news/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit News{% endblock %}

{% block body %}
    <h1>Edit News</h1>

    {{ include('news/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('news_index') }}">back to list</a>

    {{ include('news/_delete_form.html.twig') }}

{% endblock %}

templates/news/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}News {% endblock %}

{% block body %}
    <h1>News </h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th></th>
                <th>Category</th>
                <th>Title</th>
                <th>Short Description</th>
                <th>Datetime</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for itemNews in news %}
            <tr>
                <td>{% if itemNews.image == 'NO_IMG_600x600.png' %}
                        <img src="{{ asset('uploads/' ~  itemNews.image) }}" class="thumbImage"  />
                    {% else %}
                        <img src="{{ asset('uploads/images/' ~  itemNews.image) }}" class="thumbImage"  />
                    {% endif %}</td>
                <td>{{ itemNews.getCategory() }}</td>
                <td><a href="{{ path('news_show', {id: itemNews.id}) }}">{{ itemNews.title }}</a></td>
                <td>{{ itemNews.descriptionShort }}</td>
                <td>{{ itemNews.datetime ? itemNews.datetime|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('news_show', {'id': itemNews.id}) }}" class="btn btn-dark">show</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if maxPages > 1 %}
        <ul class="pagination">
            {# `«` arrow  #}
            <li {{ thisPage == 1 ? 'class="disabled"' }}>
                <a href="{{ path('news_index', {page: thisPage-1 < 1 ? 1 : thisPage-1}) }}" class="page-link">«</a>
            </li>

            {# Render each page number #}
            {% for i in 1..maxPages %}
                <li {{ thisPage == i ? 'class="page-item active"' :  'class="page-item"' }}>
                    <a href="{{ path('news_index', {page: i}) }}" class="page-link">{{ i }}</a>
                </li>
            {% endfor %}

            {# `»` arrow #}
            <li {{ thisPage == maxPages ? 'class="disabled"' }}>
                <a href="{{ path('news_index', {page: thisPage+1 <= maxPages ? thisPage+1 : thisPage}) }}" class="page-link">»</a>
            </li>
        </ul>
    {% endif %}

    <!--
    <br><hr><br>
    <a href="{{ path('news_new') }}" class="btn btn-info">Create new</a>
    -->
{% endblock %}

templates/news/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create News{% endblock %}

{% block body %}
    <h1>Create News</h1>

    {{ include('news/_form.html.twig') }}

    <a href="{{ path('news_index') }}">back to list</a>
{% endblock %}

templates/news/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}News{% endblock %}

{% block body %}
    <h1>News</h1>

    <table class="table table-striped">
        <tbody>
        <tr>
            <th rowspan="5" style="width: 160px;">
                {% if news.image == 'NO_IMG_600x600.png' %}
                    <img src="{{ asset('uploads/' ~  news.image) }}" class="thumbImageDetails" />
                {% else %}
                    <img src="{{ asset('uploads/images/' ~  news.image) }}" class="thumbImageDetails" />
                {% endif %}
            </th>
        </tr>
            <tr>
                <td class="newsTitle">{{ news.title }}</td>
            </tr>
            <tr>
                <td>{{ news.descriptionShort }}</td>
            </tr>
            <tr>
                <td>
                    <hr>
                    {{ news.descriptionLong }}</td>
            </tr>
            <tr>
                <td>{{ news.datetime ? news.datetime|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('news_index') }}">back to list</a>

    {% if is_granted('ROLE_ADMIN') %}
        <a href="/admin/?action=edit&entity=News&id={{ news.id}}" class="btn btn-info">edit</a>
    {% endif %}

    <br><hr><br>

    <!-- comment form -->
    <form class="comment-text" method="post" >
        {{ form_widget(form) }}
        <button id="contact-submit" type="submit" class="btn btn-primary">Send Comment</button>
    </form>

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="show-article-container p-3 mt-4">

                    <div class="row">
                        <div class="col-sm-12">
                            <h3><i class="pr-3 fa fa-comment"></i>Total: {{ news.comments|length }} Comments</h3>

                            {% for comment in news.comments %}
                                <div class="row">
                                    <div class="col-sm-12">

                                        <div class="comment-container d-inline-block pl-3 align-top">
                                        <span class="comment"> {{ comment.comment }}</span>

                                        </div>
                                    </div>
                                </div>
                            {% endfor %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}